"""Time bucket utilities."""

from __future__ import annotations

from datetime import datetime
from zoneinfo import ZoneInfo


class TimeBucketService:
    def __init__(self, timezone_name: str = "Asia/Taipei"):
        self.timezone_name = timezone_name
        try:
            self._tz = ZoneInfo(timezone_name)
        except Exception as exc:
            raise ValueError(f"Invalid timezone name: {timezone_name!r}") from exc

    def to_minute_bucket(self, dt: datetime) -> str:
        if dt.tzinfo is not None and self._tz is not None:
            local_dt = dt.astimezone(self._tz)
        else:
            local_dt = dt
        return local_dt.strftime("%Y-%m-%d %H:%M")


def guard_bucket_source(source_name: str) -> bool:
    if source_name != "TimeBucketService":
        raise ValueError("minute_bucket must be generated by TimeBucketService")
    return True
